cargo-features = ["edition"]

[package]
name = "futures-test"
version = "0.1.0"
authors = ["jon"]
edition = "2018"

[dependencies]
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs", branch = "master" }
hyper = "0.12.7"